### ISSUE TITLE
Cannot find request

### ISSUE THREAD

**Issue by Samueltommzy** [demsking/image-downloader#18]
i get this error in my console when i require image-downloader in my project
Error: Cannot find module 'request'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/samuel/Documents/hackerbay_backendTask/node_modules/image-downloader/index.js:3:17)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hackerbay_backendtask@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hackerbay_backendtask@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/samuel/.npm/_logs/2018-05-26T12_55_57_972Z-debug.log

**Comment by demsking** [comment]
Delete the `node_modules` directory and run `npm install`
