### ISSUE TITLE
Certain images fails

### ISSUE THREAD

**Issue by fjeddy** [demsking/image-downloader#19]
```
const { filename, image } = await Download.image( {
  url: 'https://crafatar.com/renders/body/5b64d30d-25d8-4f9d-85bc-55e2c1e6b99f.png?scale=10',
  dest: './data/skins'
} );
```
returns the following error

```
Error: Image loading error - 201. URL: https://crafatar.com/renders/body/5b64d30d-25d8-4f9d-85bc-55e2c1e6b99f.png?scale=10
    at Request.request [as _callback] (/Users/*/Sites/*.no/*.public/node_modules/image-downloader/index.js:53:15)
    at Request.self.callback (/Users/*/Sites/*.no/*.public/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/Users/*/Sites/*.no/*.public/node_modules/request/request.js:1157:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/Users/*/Sites/*.no/*.public/node_modules/request/request.js:1079:12)
    at Object.onceWrapper (events.js:275:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1091:14)
    at process._tickCallback (internal/process/next_tick.js:174:19
```

`https://crafatar.com/renders/head/5b64d30d-25d8-4f9d-85bc-55e2c1e6b99f.png?scale=10`

And it suddenly works, minimal change, same site, same API, same everything, except a different result.

**Comment by fjeddy** [comment]
Seems like the cause is that the endpoint can send both the status codes `200` and `201` while this library solely accept `200`

**Comment by fjeddy** [comment]
Pull requests #20 fixes this issue, please get it on NPM! 😄

**Comment by demsking** [comment]
PR #20 merged
